### ISSUE TITLE
Unable to import module 'transform': cannot import name '_imaging'

### ISSUE THREAD

**Issue by joarleymoraes** [caffeinetv/snappy#15]
this error was introduced in #14 (in the new image validation step) and it only happens in the Lambda env. (all tests pass locally and on travis)
